const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE';
const SET_DO_SEARCH = 'SET_DO_SEARCH';
const SET_CLEAN_ACCOUNT_FIND_DATA = 'SET_CLEAN_ACCOUNT_FIND_DATA';
const SET_CUSTOMERS = 'SET_CUSTOMERS';
const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER';
const SET_CLEAN_SELECTED_SUBSCRIBE = 'SET_CLEAN_SELECTED_SUBSCRIBE';
const SET_SELECTED_SUBSCRIBE = 'SET_SELECTED_SUBSCRIBE';
const SET_ADD_DATA_SELECTED_SUBSCRIBE = 'SET_ADD_DATA_SELECTED_SUBSCRIBE';
const SET_FILTERS = 'SET_FILTERS';

const ADD_TEMP_ORDER = 'ADD_TEMP_ORDER';

export {
  SET_DO_SEARCH,
  SET_SEARCH_TYPE,
  SET_CLEAN_ACCOUNT_FIND_DATA,
  SET_CUSTOMERS,
  SET_CURRENT_CUSTOMER,
  SET_CLEAN_SELECTED_SUBSCRIBE,
  SET_SELECTED_SUBSCRIBE,
  SET_ADD_DATA_SELECTED_SUBSCRIBE,
  SET_FILTERS,
  ADD_TEMP_ORDER
}