const SET_PRODUCTS_SELECTED = "SET_PRODUCTS_SELECTED";
const REMOVE_PRODUCT = "REMOVE_PRODUCT";
const CLEAN_PRODUCTS_SELECTED = "CLEAN_PRODUCTS_SELECTED";
const SET_ADDONS_SELECTED = "SET_ADDONS_SELECTED";
const REMOVE_ADDON_SELECTED = "REMOVE_ADDON_SELECTED";
const SET_PRODUCTS_SELECTED_TOTAL_AMOUNT = "SET_PRODUCTS_SELECTED_TOTAL_AMOUNT";
const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";
const RESET_SCHEDULE = "RESET_SCHEDULE";

export {
  SET_PRODUCTS_SELECTED,
  REMOVE_PRODUCT,
  CLEAN_PRODUCTS_SELECTED,
  SET_ADDONS_SELECTED,
  REMOVE_ADDON_SELECTED,
  SET_PRODUCTS_SELECTED_TOTAL_AMOUNT,
  UPDATE_SCHEDULE,
  RESET_SCHEDULE
};
